### ISSUE TITLE
Error on production server

### ISSUE THREAD

**Issue by andrew-ireland** [austenc/statamic-instagram-feed#11]
On my local laravel valet env this plugin appears to work great! Thanks for your work on this 😊

Unfortunately though, on my production server I can't get any output using this plugin, and just see a broken url with an unknown src.

I am using a dummy account with 2FA turned off. I am racking my brain trying to figure out why it won't work in production — are there any specific addon logs I could look at to find the issue?

**Comment by andrew-ireland** [comment]
Actually, I did notice this in my general logs (though it could be caused during installing & uninstalling when debugging). Do you have any idea what this means?

`[2021-02-09 17:36:33] production.ERROR: include(/home/robryanprojectscom/robryanprojects.com/vendor/austenc/statamic-instagram-feed/src/ServiceProvider.php): failed to open stream: No such file or directory {"exception":"[object] (ErrorException(code: 0): include(/home/robryanprojectscom/robryanprojects.com/vendor/austenc/statamic-instagram-feed/src/ServiceProvider.php): failed to open stream: No such file or directory at /home/robryanprojectscom/robryanprojects.com/vendor/composer/ClassLoader.php:476)
[stacktrace]
#0 /home/robryanprojectscom/robryanprojects.com/vendor/composer/ClassLoader.php(476): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /home/robryanprojectscom/robryanprojects.com/vendor/composer/ClassLoader.php(476): include()
#2 /home/robryanprojectscom/robryanprojects.com/vendor/composer/ClassLoader.php(344): Composer\\Autoload\\includeFile()
#3 [internal function]: Composer\\Autoload\\ClassLoader->loadClass()
#4 /home/robryanprojectscom/robryanprojects.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(690): spl_autoload_call()
#5 /home/robryanprojectscom/robryanprojects.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(624): Illuminate\\Foundation\\Application->resolveProvider()
#6 /home/robryanprojectscom/robryanprojects.com/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(75): Illuminate\\Foundation\\Application->register()
#7 /home/robryanprojectscom/robryanprojects.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(604): Illuminate\\Foundation\\ProviderRepository->load()
#8 /home/robryanprojectscom/robryanprojects.com/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php(17): Illuminate\\Foundation\\Application->registerConfiguredProviders()
#9 /home/robryanprojectscom/robryanprojects.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(230): Illuminate\\Foundation\\Bootstrap\\RegisterProviders->bootstrap()
#10 /home/robryanprojectscom/robryanprojects.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(152): Illuminate\\Foundation\\Application->bootstrapWith()
#11 /home/robryanprojectscom/robryanprojects.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(136): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
#12 /home/robryanprojectscom/robryanprojects.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#13 /home/robryanprojectscom/robryanprojects.com/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()
#14 {main}
"} `

**Comment by andrew-ireland** [comment]
I thought I'd fixed this, but after reinstalling the site on my production server I'm seeing the issue again.

Opening it in case anyone sees it and can help...
