### ISSUE TITLE
No output with Statamic 3.0.16

### ISSUE THREAD

**Issue by wm-simon** [austenc/statamic-instagram-feed#8]
Hey,
there is not output anymore. Don't know, since which version this happened.
Statamic 3.0.16
Insta Feed 2.2.0

Error:
```
Unknown error, please report it with a GitHub issue. Client error: `POST https://www.instagram.com/accounts/login/ajax/` resulted in a `429 -` response: {"message": "", "spam": true, "status": "fail"} #0 /var/www/vhosts/domain.com/httpdocs/vendor/pgrimaud/instagram-user-feed/src/Instagram/Api.php(96): Instagram\Auth\Login->process() #1 /var/www/vhosts/domain.com/httpdocs/vendor/austenc/statamic-instagram-feed/src/Tags/InstagramFeed.php(20): Instagram\Api->login() #2 [internal function]: Austenc\InstagramFeed\Tags\InstagramFeed->index() #3 /var/www/vhosts/domain.com/httpdocs/vendor/statamic/cms/src/View/Antlers/Engine.php(152): call_user_func() #4 [internal function]: Statamic\View\Antlers\Engine::renderTag() #5 /var/www/vhosts/domain.com/httpdocs/vendor/statamic/cms/src/View/Antlers/Parser.php(576): call_user_func_array() #6 /var/www/vhosts/domain.com/httpdocs/vendor/statamic/cms/src/View/Antlers/Parser.php(177): Statamic\View\Antlers\Parser->parseCallbackTags() #7 /var/www/vhosts/domain.com/httpdocs/vendor/statamic/cms/src/View/Antlers/Parser.php(132): Statamic\View\Antlers\Parser->parse() #8 /var/www/vhosts/domain.com/httpdocs/vendor/statamic/cms/src/View/Antlers/Engine.php(89): Statamic\View\Antlers\Parser->parseView() #9 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/View/View.php(143): Statamic\View\Antlers\Engine->get() #10 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/View/View.php(126): Illuminate\View\View->getContents() #11 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\View\View->renderContents() #12 /var/www/vhosts/domain.com/httpdocs/vendor/statamic/cms/src/Tags/Partial.php(20): Illuminate\View\View->render() #13 /var/www/vhosts/domain.com/httpdocs/vendor/statamic/cms/src/Tags/Tags.php(132): Statamic\Tags\Partial->wildcard() #14 [internal function]: Statamic\Tags\Tags->__call() #15 /var/www/vhosts/domain.com/httpdocs/vendor/statamic/cms/src/View/Antlers/Engine.php(152): call_user_func() #16 [internal function]: Statamic\View\Antlers\Engine::renderTag() #17 /var/www/vhosts/domain.com/httpdocs/vendor/statamic/cms/src/View/Antlers/Parser.php(576): call_user_func_array() #18 /var/www/vhosts/domain.com/httpdocs/vendor/statamic/cms/src/View/Antlers/Parser.php(177): Statamic\View\Antlers\Parser->parseCallbackTags() #19 /var/www/vhosts/domain.com/httpdocs/vendor/statamic/cms/src/View/Antlers/Parser.php(132): Statamic\View\Antlers\Parser->parse() #20 /var/www/vhosts/domain.com/httpdocs/vendor/statamic/cms/src/View/Antlers/Engine.php(89): Statamic\View\Antlers\Parser->parseView() #21 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/View/View.php(143): Statamic\View\Antlers\Engine->get() #22 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/View/View.php(126): Illuminate\View\View->getContents() #23 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\View\View->renderContents() #24 /var/www/vhosts/domain.com/httpdocs/vendor/statamic/cms/src/View/View.php(74): Illuminate\View\View->render() #25 /var/www/vhosts/domain.com/httpdocs/vendor/statamic/cms/src/Http/Responses/DataResponse.php(144): Statamic\View\View->render() #26 /var/www/vhosts/domain.com/httpdocs/vendor/statamic/cms/src/Http/Responses/DataResponse.php(45): Statamic\Http\Responses\DataResponse->contents() #27 /var/www/vhosts/domain.com/httpdocs/vendor/statamic/cms/src/Structures/Page.php(288): Statamic\Http\Responses\DataResponse->toResponse() #28 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(734): Statamic\Structures\Page->toResponse() #29 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(721): Illuminate\Routing\Router::toResponse() #30 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\Routing\Router->prepareResponse() #31 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Routing\Router->Illuminate\Routing\{closure}() #32 /var/www/vhosts/domain.com/httpdocs/vendor/statamic/cms/src/StaticCaching/Middleware/Cache.php(29): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #33 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Statamic\StaticCaching\Middleware\Cache->handle() #34 /var/www/vhosts/domain.com/httpdocs/vendor/statamic/cms/src/Http/Middleware/Localize.php(22): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #35 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Statamic\Http\Middleware\Localize->handle() #36 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #37 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Routing\Middleware\SubstituteBindings->handle() #38 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(77): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #39 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle() #40 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #41 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\View\Middleware\ShareErrorsFromSession->handle() #42 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #43 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Session\Middleware\StartSession->handle() #44 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #45 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle() #46 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #47 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\EncryptCookies->handle() #48 /var/www/vhosts/domain.com/httpdocs/vendor/statamic/cms/src/StaticCaching/Middleware/Retrieve.php(34): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #49 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Statamic\StaticCaching\Middleware\Retrieve->handle() #50 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #51 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\Pipeline\Pipeline->then() #52 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\Routing\Router->runRouteWithinStack() #53 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\Routing\Router->runRoute() #54 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\Routing\Router->dispatchToRoute() #55 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\Routing\Router->dispatch() #56 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}() #57 /var/www/vhosts/domain.com/httpdocs/vendor/statamic/cms/src/Http/Middleware/CheckMultisite.php(14): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #58 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Statamic\Http\Middleware\CheckMultisite->handle() #59 /var/www/vhosts/domain.com/httpdocs/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(19): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #60 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Statamic\Http\Middleware\PoweredByHeader->handle() #61 /var/www/vhosts/domain.com/httpdocs/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #62 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Barryvdh\Debugbar\Middleware\InjectDebugbar->handle() #63 /var/www/vhosts/domain.com/httpdocs/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #64 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\Proxy\TrustProxies->handle() #65 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #66 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle() #67 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #68 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle() #69 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #70 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle() #71 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #72 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle() #73 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #74 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\Pipeline\Pipeline->then() #75 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter() #76 /var/www/vhosts/domain.com/httpdocs/public/index.php(55): Illuminate\Foundation\Http\Kernel->handle() #77 {main}
```

**Comment by wm-simon** [comment]
I'm sorry, client changed the password without saying this to me. Closed.

**Comment by wm-simon** [comment]
Hmm, I have this problem now on multiple sites. I don't think this depends to the password change.

**Comment by austenc** [comment]
Hey @wm-simon, are you still having this issue? 

I'm not really sure, but it looks like you might not have a cache driver setup correctly? If that is the case, the underlying [Instagram composer package](https://github.com/pgrimaud/instagram-user-feed) might be trying to log in with each page request, causing Instagram to think it is a spam login from too many requests.

As far as fixing this, please let me know if you have other information to present (and I'll reopen it), or you might try digging in to the [other package](https://github.com/pgrimaud/instagram-user-feed) to see if there are other users with your problem. 

Thanks!
